version: '3.4'

services:
  apigendoc:
    image: apigendoc
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080

  # for convert word to pdf
  gotenberg:
    image: gotenberg/gotenberg:7
